services: #m
  c1:
    build: .
    image: mon-app-socket
    container_name: c1
    ports:
      - "5000:5000"       # Public
      - "5001-5010:5001-5010" # Réservé pour le privé
    environment:
      - MY_NAME=c1
      # Local : on utilise le nom du service Docker
      - ADDR_C1=c1:5000
      - ADDR_C2=c2:5000
      # On passe par l'IP pour la deuxième vm
      - ADDR_C3=192.168.17.20:6003
      - ADDR_C4=192.168.17.20:6004

  c2:
    image: mon-app-socket
    container_name: c2
    ports:
      - "5000:5000"       # Public
      - "5001-5010:5001-5010" # Réservé pour le privé
    environment:
      - MY_NAME=c2
      - ADDR_C1=c1:5000
      - ADDR_C2=c2:5000
      - ADDR_C3=192.168.1.20:6003
      - ADDR_C4=192.168.1.20:6004
