services:
  registry:
    image: registry:2
    container_name: registry
    ports:
      - "6000:5000"
    restart: always
  c3:
    build: .
    image: registry:6000/mon-app-socket
    container_name: c3
    ports:
      - "5003:5000"       # Public
      - "5300-5310:5300-5310" # Réservé pour le privé
    environment:
      - MY_NAME=c3
      - MY_PUBLIC_PORT=5000
      - PRIVATE_RANGE_START=5300
      # Local : on utilise le nom du service Docker
      - ADDR_C3=c3:5000
      - ADDR_C4=c4:5000
      # On passe par l'ip
      - ADDR_C1=192.168.200.13:5001
      - ADDR_C2=192.168.200.13:5002

  c4:
    image: registry:6000/mon-app-socket
    container_name: c4
    ports:
      - "5004:5000"       # Public
      - "5400-5410:5400-5410" # Réservé pour le privé
    environment:
      - MY_NAME=c4
      - MY_PUBLIC_PORT=5000
      - PRIVATE_RANGE_START=5400
      - ADDR_C3=c3:5000
      - ADDR_C4=c4:5000
      - ADDR_C1=192.168.200.13:5001
      - ADDR_C2=192.168.200.13:5002
