services: #m
  c3:
    build: .
    image: mon-app-socket
    container_name: c3
    ports:
      - "5003:5000"       # Public
      - "5300-5310:5001-5010" # Réservé pour le privé
    environment:
      - MY_NAME=c3
      # Local : on utilise le nom du service Docker
      - ADDR_C3=c3:5003
      - ADDR_C4=c4:5004
      # On passe par l'ip
      - ADDR_C1=192.168.200.13:6001
      - ADDR_C2=192.168.200.13:6002

  c4:
    image: mon-app-socket
    container_name: c4
    ports:
      - "5004:5000"       # Public
      - "5400-5410:5001-5010" # Réservé pour le privé
    environment:
      - MY_NAME=c4
      - ADDR_C3=c3:5003
      - ADDR_C4=c4:5004
      - ADDR_C1=192.168.200.13:5001
      - ADDR_C2=192.168.200.13:5002
